import { motion } from "framer-motion";
import { Bird, Clock, MapPin, Plane, Car, Utensils, Waves, BedDouble } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import CallToAction from "@/components/home/CallToAction";
import lodgeFlyer from "@/assets/tembo-safari-lodge-rates.jpeg";
import kidepoImage from "@/assets/kidepo-wildlife.jpg";

const features=[{icon:BedDouble,title:"Rest well",text:"Singles, doubles, twins, and triples in standard rooms and traditional grass-thatched cottages."},{icon:Waves,title:"Channel views",text:"Look towards the Kazinga Channel, where hippos, birds, and other wildlife are frequent visitors."},{icon:Utensils,title:"Eat onsite",text:"Enjoy local and continental dishes at the lodge restaurant, with a bar available for guests."},{icon:Bird,title:"Explore nearby",text:"Boat cruises, guided game drives, nature walks, bird watching, biking, and fishing tours."}];
const About=()=> <div className="min-h-screen bg-background"><Navbar/>
<section className="relative overflow-hidden bg-primary py-32 text-primary-foreground md:py-40"><div className="absolute inset-0 opacity-25"><img src={kidepoImage} alt="Wildlife in Queen Elizabeth National Park" className="h-full w-full object-cover"/></div><div className="safari-container relative z-10 text-center"><span className="mb-6 inline-block rounded-full bg-secondary/20 px-5 py-2 text-sm font-semibold uppercase text-secondary">The Lodge</span><h1 className="mb-6 font-display text-5xl font-bold md:text-7xl">Close to nature. <span className="text-secondary">Easy to call home.</span></h1><p className="mx-auto max-w-2xl text-xl text-primary-foreground/90">A friendly, budget-conscious stay in Katunguru, inside Queen Elizabeth National Park.</p></div></section>
<section className="safari-section"><div className="safari-container grid items-center gap-12 lg:grid-cols-2"><div><span className="safari-badge mb-4">Welcome to Tembo</span><h2 className="safari-heading mb-6">A front-row seat to the Kazinga Channel</h2><div className="space-y-4 safari-text"><p>Tembo Safari Lodge is located in Katunguru, only 300 metres from the wildlife-rich Kazinga Channel.</p><p>Our traditional cottages and standard rooms offer the essentials for a comfortable park stay: private balconies, mosquito nets, self-contained bathrooms, and hot showers.</p><p>Whether you arrive for a quiet night, a family visit, or days of wildlife activities, our team is ready to help you settle in.</p></div></div><div className="overflow-hidden rounded-lg shadow-dramatic"><img src={lodgeFlyer} alt="Tembo Safari Lodge rooms and dining" className="w-full object-cover"/></div></div></section>
<section className="safari-section bg-muted"><div className="safari-container"><div className="mb-12 text-center"><span className="safari-badge mb-4">At the lodge</span><h2 className="safari-heading">Everything you need</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{features.map((item,index)=><motion.article key={item.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="bg-card p-7 shadow-soft"><item.icon className="mb-5 text-primary" size={32}/><h3 className="mb-3 text-xl font-bold">{item.title}</h3><p className="text-muted-foreground">{item.text}</p></motion.article>)}</div></div></section>
<section className="safari-section"><div className="safari-container"><div className="mb-12 max-w-2xl"><span className="safari-badge mb-4">Getting here</span><h2 className="safari-heading mb-5">Travel to Katunguru</h2><p className="safari-text">Find us off the Ntungamo–Katunguru Road inside Queen Elizabeth National Park.</p></div><div className="grid gap-6 md:grid-cols-3"><div className="border-t-2 border-secondary pt-6"><MapPin className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">Address</h3><p className="text-muted-foreground">Katunguru, Queen Elizabeth National Park, Uganda</p></div><div className="border-t-2 border-secondary pt-6"><Car className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">By road</h3><p className="text-muted-foreground">About 5–6 hours (384 km) from Kampala via Mbarara and Bushenyi.</p></div><div className="border-t-2 border-secondary pt-6"><Plane className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">By air</h3><p className="text-muted-foreground">About 1 hour from Entebbe to Kasese Airstrip, followed by a short transfer.</p></div></div></div></section><CallToAction/><Footer/></div>;
export default About;
