import { motion } from "framer-motion";
import { Bird, MapPin, Plane, Car, Utensils, Waves, BedDouble, Heart, Users } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import CallToAction from "@/components/home/CallToAction";
import lodgeFlyer from "@/assets/tembo-safari-lodge-rates.jpeg";
import kidepoImage from "@/assets/kidepo-wildlife.jpg";
import lodgeImage from "@/assets/image-3.jpeg";
import diningImage from "@/assets/image-1.jpeg";
import sunsetImage from "@/assets/image-2.jpeg";

const features=[{icon:BedDouble,title:"Rest well",text:"Singles, doubles, twins, and triples in standard rooms and traditional grass-thatched cottages."},{icon:Waves,title:"Channel views",text:"Look towards the Kazinga Channel, where hippos, birds, and other wildlife are frequent visitors."},{icon:Utensils,title:"Eat onsite",text:"Enjoy local and continental dishes at the lodge restaurant, with a bar available for guests."},{icon:Bird,title:"Explore nearby",text:"Boat cruises, guided game drives, nature walks, bird watching, biking, and fishing tours."}];
const team=[{title:"Guest welcome",text:"The front-of-house team helps you settle in, find your room, and plan each day around the park.",image:lodgeImage,icon:Heart},{title:"Guides & local hosts",text:"Our local activity partners know the channels, tracks, and rhythms of Queen Elizabeth National Park.",image:sunsetImage,icon:Users},{title:"Kitchen & housekeeping",text:"The people behind every comfortable room and shared meal keep the lodge warm, practical, and cared for.",image:diningImage,icon:Utensils}];
const About=()=> <div className="min-h-screen bg-background"><Navbar/>
<section className="relative overflow-hidden bg-primary py-32 text-primary-foreground md:py-40"><div className="absolute inset-0 opacity-25"><img src={kidepoImage} alt="Wildlife in Queen Elizabeth National Park" className="h-full w-full object-cover"/></div><div className="safari-container relative z-10 text-center"><span className="mb-6 inline-block rounded-full bg-secondary/20 px-5 py-2 text-sm font-semibold uppercase text-secondary">The Lodge</span><h1 className="mb-6 font-display text-5xl font-bold md:text-7xl">Close to nature. <span className="text-secondary">Easy to call home.</span></h1><p className="mx-auto max-w-2xl text-xl text-primary-foreground/90">A friendly, budget-conscious stay in Katunguru, inside Queen Elizabeth National Park.</p></div></section>
<section className="safari-section"><div className="safari-container grid items-center gap-12 lg:grid-cols-2"><div><span className="safari-badge mb-4">Our story</span><h2 className="safari-heading mb-6">A lodge shaped by the river, the park, and its people</h2><div className="space-y-4 safari-text"><p>Tembo Safari Lodge grew from a simple idea: give travellers a welcoming place to pause between the wildlife of Queen Elizabeth National Park and the living communities around Katunguru.</p><p>Set just 300 metres from the Kazinga Channel, the lodge is close enough for boat cruises, game drives, and riverside mornings to become part of everyday life. The sound of water, birds, and passing hippos is part of the address.</p><p>Today, Tembo remains an easy-going lodge built around local hospitality. We keep the stay comfortable and practical, while leaving room for the experiences that brought you to Uganda in the first place.</p></div></div><div className="overflow-hidden rounded-lg shadow-dramatic"><img src={lodgeImage} alt="Tembo Safari Lodge surrounded by the Queen Elizabeth landscape" className="aspect-[4/3] w-full object-cover"/></div></div></section>
<section className="safari-section bg-muted"><div className="safari-container"><div className="mb-12 text-center"><span className="safari-badge mb-4">At the lodge</span><h2 className="safari-heading">Everything you need</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{features.map((item,index)=><motion.article key={item.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="bg-card p-7 shadow-soft"><item.icon className="mb-5 text-primary" size={32}/><h3 className="mb-3 text-xl font-bold">{item.title}</h3><p className="text-muted-foreground">{item.text}</p></motion.article>)}</div></div></section>
<section className="safari-section bg-muted"><div className="safari-container"><div className="mb-12 text-center"><span className="safari-badge mb-4">At the lodge</span><h2 className="safari-heading">Everything you need</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{features.map((item,index)=><motion.article key={item.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="bg-card p-7 shadow-soft"><item.icon className="mb-5 text-primary" size={32}/><h3 className="mb-3 text-xl font-bold">{item.title}</h3><p className="text-muted-foreground">{item.text}</p></motion.article>)}</div></div></section>
<section className="safari-section"><div className="safari-container"><div className="mb-12 max-w-3xl"><span className="safari-badge mb-4">The people of Tembo</span><h2 className="safari-heading mb-5">A team that makes the stay feel easy</h2><p className="safari-text">Our lodge team brings together welcome, local knowledge, thoughtful rooms, and food shared around the day's stories. These images show the places and work that shape the guest experience.</p></div><div className="grid gap-6 md:grid-cols-3">{team.map((member,index)=><motion.article key={member.title} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="overflow-hidden rounded-lg bg-card shadow-soft"><img src={member.image} alt={member.title} className="aspect-[4/3] w-full object-cover"/><div className="p-6"><member.icon className="mb-4 text-primary" size={28}/><h3 className="mb-3 text-xl font-bold">{member.title}</h3><p className="text-muted-foreground">{member.text}</p></div></motion.article>)}</div></div></section>
<section className="safari-section"><div className="safari-container"><div className="mb-12 max-w-2xl"><span className="safari-badge mb-4">Getting here</span><h2 className="safari-heading mb-5">Travel to Katunguru</h2><p className="safari-text">Find us off the Ntungamo–Katunguru Road inside Queen Elizabeth National Park.</p></div><div className="grid gap-6 md:grid-cols-3"><div className="border-t-2 border-secondary pt-6"><MapPin className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">Address</h3><p className="text-muted-foreground">Katunguru, Queen Elizabeth National Park, Uganda</p></div><div className="border-t-2 border-secondary pt-6"><Car className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">By road</h3><p className="text-muted-foreground">About 5–6 hours (384 km) from Kampala via Mbarara and Bushenyi.</p></div><div className="border-t-2 border-secondary pt-6"><Plane className="mb-4 text-primary"/><h3 className="mb-2 text-xl font-bold">By air</h3><p className="text-muted-foreground">About 1 hour from Entebbe to Kasese Airstrip, followed by a short transfer.</p></div></div></div></section><CallToAction/><Footer/></div>;
export default About;
